add_newline = false
format = "$username$hostname$directory$git_branch$git_state$git_status$cmd_duration$line_break$python$env_var$character"

[env_var.CONTAINER_ID]
#format = "[ âš™ï¸]($style)[î‚°](fg:white bg:#003543)"
format = "[ğŸ“¦]($style)"
#style = "fg:#d70a53 bg:white"
variable = "CONTAINER_ID"
disabled = false

[env_var.HOSTSHELL]
format = "[ğŸ›¡ï¸]($style)"
#variable = "CONTAINER_ID"
disabled = false

[character]
error_symbol = "[â¯](red)"
success_symbol = "[â¯](blue)"
vimcmd_symbol = "[â®](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[directory]
style = "blue"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_state]
format = "\\([$state( $progress_current/$progress_total)]($style)\\) "
style = "bright-black"

[git_status]
conflicted = "â€‹"
deleted = "â€‹"
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
modified = "â€‹"
renamed = "â€‹"
staged = "â€‹"
stashed = "â‰¡"
style = "cyan"
untracked = "â€‹"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
